name: List of file availability
on:
 workflow_dispatch:
jobs:
    List-files:
        runs-on: ubuntu-latest
        steps:
        - name: Location path
          run: |
            echo "Current working directory"
            pwd
        - name: list of files
          run: |
            echo " List of files in the repository"
            ls -R
        - name: Give me the repo name
          run: |
            echo "Repository name: https/github.com/${{ github.repository}}.git"