name: Without actions
on:
  workflow_dispatch:
jobs:
    manual-setup:
        runs-on: ubuntu-latest
        steps:
        - name: Manually Cloning the repo
          run: |
            echo "Cloning the repository manually"
            git clone https/github.com/${{ github.repository}}.git .
            ls -la
            echo "==============================="
            echo "Print working directory"
            pwd
         